### ISSUE TITLE
Question about the preprocessed data

### ISSUE THREAD

**Issue by Wangzy200102** [yec22/Indoor-Recon#3]
Could you please introduce how to get the preprocessed dataset, especially 'uncertainty weight for each view'？

**Comment by yec22** [comment]
Thank you for your interest in our work.

Please refer to `scripts/preprocess.sh` for step-by-step data processing.

For the weight of our uncertainty estimation module (U-Net), here is the download link: https://drive.google.com/file/d/18mvYnUISLIG9yKdbWeKgHiB5yZ_6Eym6/view?usp=sharing
