### ISSUE TITLE
Uncertainty Estimation Module--UNet weight

### ISSUE THREAD

**Issue by yafeiya** [yec22/Indoor-Recon#4]
Hello，Glad to see your excellent work, but we cannot reproduce your work .
I have a question Looking forward to receiving a reply. 
In your code preprocess.sh, we tried to get ckpt_epoch_5.pth of Unet.
![image](https://github.com/yec22/Fine-Grained-Indoor-Recon/assets/102225985/019e2cf0-d144-4ff3-96d2-334fc8461d71)

Could you tell me how to achieve this process in your paper?
![image](https://github.com/yec22/Fine-Grained-Indoor-Recon/assets/102225985/e692592e-7067-4506-9bcf-6f928b089c3b)

**Comment by yec22** [comment]
Thank you for your interest in our work.

Here is the download link of ckpt_epoch_5.pth: https://drive.google.com/file/d/18mvYnUISLIG9yKdbWeKgHiB5yZ_6Eym6/view?usp=sharing

**Comment by yafeiya** [comment]
Very grateful，it helps me a lot.
